<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>edu.softserveinc.healthbody</groupId>
	<artifactId>HealthBody-WebClient</artifactId>

	<packaging>war</packaging>
	<version>1.0</version>

	<name>HealthBody-WebClient</name>

	<url>http://maven.apache.org</url>
	<properties>
		<!-- - - - - - Encoding - - - - - -->
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.resources.plugin.version>2.7</maven.resources.plugin.version>
		<!-- - - - - - Java - - - - - -->
		<jdk.source.version.local>1.8</jdk.source.version.local>
		<jdk.compiler.version.local>1.8</jdk.compiler.version.local>
		<jdk.source.version.openshift>1.6</jdk.source.version.openshift>
		<jdk.compiler.version.openshift>1.6</jdk.compiler.version.openshift>
		<maven.compiler.plugin.version>3.3</maven.compiler.plugin.version>
		<!-- - - - - - Logger - - - - - -->
		<org.slf4j.version>1.7.21</org.slf4j.version>
		<!-- - - - - - Test - - - - - -->
		<org.testng.version>6.9.10</org.testng.version>
		<testng.reports.directory>./target/surefire-reports/test-output</testng.reports.directory>
		<maven.surefire.plugin.version>2.19.1</maven.surefire.plugin.version>
		<!-- - - - - - Web - - - - - -->
		<maven.war.plugin.version>2.6</maven.war.plugin.version>
		<cxf.version>2.2.3</cxf.version>
		<!-- - - - - - Google API - - - - - -->
		<google.api.client.version>1.22.0</google.api.client.version>
		<!-- - - - Parsing XML & JSON - - - -->
		<dom4j.version>1.6.1</dom4j.version>
		<gson.version>2.7</gson.version>
		<!-- - - - Spring Framework - - - -->
		<org.springframework.version>4.3.1.RELEASE</org.springframework.version>
		<org.springframework.security.version>4.1.1.RELEASE</org.springframework.security.version>
		<!-- - - - - - JPA - - - - - -->
		<spring-data-jpa.version>1.10.1.RELEASE</spring-data-jpa.version>
		<postgresql.connector.version>9.4-1200-jdbc41</postgresql.connector.version>
		<hibernate.version>5.0.0.Final</hibernate.version>
		<!-- - - - - - Variables - - - - - -->
		<my.text>Hello World!</my.text>
	</properties>


	<dependencies>
		<!-- - - - - - Tests - - - - - -->
		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>${org.testng.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- - - - Logger - - - -->
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>${org.slf4j.version}</version>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.16.10</version>
			<scope>provided</scope>
		</dependency>

		<!-- <dependency> <groupId>org.seleniumhq.selenium</groupId> <artifactId>selenium-server</artifactId> 
			<version>2.53.0</version> </dependency> <dependency> <groupId>org.seleniumhq.selenium</groupId> 
			<artifactId>selenium-java</artifactId> <version>2.53.0</version> </dependency> -->
		<!-- - - - Google API - - - -->
		<dependency>
			<groupId>com.google.api-client</groupId>
			<artifactId>google-api-client</artifactId>
			<version>${google.api.client.version}</version>
		</dependency>
		<!-- - - - Java Servlets - - - -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jstl</groupId>
			<artifactId>jstl</artifactId>
			<version>1.2</version>
		</dependency>
		<!-- - - - Parsing XML & JSON - - - -->
		<dependency>
			<groupId>dom4j</groupId>
			<artifactId>dom4j</artifactId>
			<version>${dom4j.version}</version>
			<type>jar</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>com.google.code.gson</groupId>
			<artifactId>gson</artifactId>
			<version>${gson.version}</version>
		</dependency>

		<!-- - - - Spring - - - -->
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-core</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-web</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webmvc</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
			<version>${org.springframework.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-web</artifactId>
			<version>${org.springframework.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-config</artifactId>
			<version>${org.springframework.security.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.security.oauth</groupId>
			<artifactId>spring-security-oauth2</artifactId>
			<version>2.0.10.RELEASE</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-databind -->
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
			<version>2.8.1</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/net.aksingh/owm-japis -->
		<dependency>
			<groupId>net.aksingh</groupId>
			<artifactId>owm-japis</artifactId>
			<version>2.5.0.3</version>
		</dependency>

		<!-- - - - - - JPA - - - - - -->
		<dependency>
			<groupId>org.springframework.data</groupId>
			<artifactId>spring-data-jpa</artifactId>
			<version>${spring-data-jpa.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-orm</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-tx</artifactId>
			<version>${org.springframework.version}</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<version>${postgresql.connector.version}</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-entitymanager</artifactId>
			<version>${hibernate.version}</version>
		</dependency>
		<dependency>
			<groupId>javax.mail</groupId>
			<artifactId>mail</artifactId>
			<version>1.4.7</version>
		</dependency>
		<dependency>
			<groupId>javax.validation</groupId>
			<artifactId>validation-api</artifactId>
			<version>2.0.1.Final</version>
		</dependency>
		<dependency>
			<groupId>commons-validator</groupId>
			<artifactId>commons-validator</artifactId>
			<version>1.5.1</version>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.2.4.Final</version>
		</dependency>
		<!-- https://mvnrepository.com/artifact/org.apache.httpcomponents/httpclient -->
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.2</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>${maven.resources.plugin.version}</version>
				<configuration>
					<encoding>UTF-8</encoding>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>
				<version>${maven.war.plugin.version}</version>
				<configuration>
					<!-- <warSourceDirectory>WebContent</warSourceDirectory> -->
					<failOnMissingWebXml>false</failOnMissingWebXml>
					<warName>HealthBody-WebClient</warName>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>jaxws-maven-plugin</artifactId>
				<version>2.4.1</version>
				<!-- <executions> <execution> <id>wsimport-from-jdk</id> <goals> <goal>wsimport</goal> 
					</goals> </execution> </executions> -->
				<configuration>
					<vmArgs>
						<vmArg>-Djavax.xml.accessExternalDTD=all</vmArg>
						<vmArg>-Djavax.xml.accessExternalSchema=all</vmArg>
					</vmArgs>
					<!-- using wsdl from an url -->
					<wsdlUrls>
						<wsdlUrl>
							http://localhost:8080/HealthBody-WebService/HealthBodyService?wsdl
						</wsdlUrl>
					</wsdlUrls>
					<!-- Keep generated files -->
					<keep>true</keep>
					<!-- Package name -->
					<packageName>edu.softserveinc.healthbody.webclient.healthbody.webservice</packageName>
					<!-- generated source files destination -->
					<sourceDestDir>src/main/java</sourceDestDir>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>local</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<build>
				<plugins>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>${maven.compiler.plugin.version}</version>
						<configuration>
							<source>${jdk.source.version.local}</source>
							<target>${jdk.compiler.version.local}</target>
							<encoding>UTF-8</encoding>
						</configuration>
					</plugin>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>${maven.surefire.plugin.version}</version>
						<configuration>
							<argLine>-Xms512m -Xmx1024m</argLine>
							<skipTests>false</skipTests>
							<!-- <argLine>${surefireArgLine}</argLine> -->
							<systemPropertyVariables>
								<surefire.reports.directory>
									${testng.reports.directory}
								</surefire.reports.directory>
								<surefire.reports.profile>
									${my.text} profile id
									=${project.activeProfiles[0].id}
								</surefire.reports.profile>
							</systemPropertyVariables>
							<suiteXmlFiles>
								<!-- <suiteXmlFile>testng.xml</suiteXmlFile> -->
								<file>testng.xml</file>
							</suiteXmlFiles>
							<reportsDirectory>${testng.reports.directory}</reportsDirectory>
						</configuration>
					</plugin>

					<plugin>
						<groupId>com.google.code.echo-maven-plugin</groupId>
						<artifactId>echo-maven-plugin</artifactId>
						<version>1.0.0</version>
						<inherited>false</inherited>
						<configuration>
							<message>Hello, ${localRepository} artifactId =
								${project.artifactId}</message>
						</configuration>
						<executions>
							<execution>
								<phase>test</phase>
								<goals>
									<goal>echo</goal>
								</goals>
							</execution>
						</executions>
					</plugin>

				</plugins>
			</build>
		</profile>

		<profile>
			<id>openshift</id>
			<build>
				<plugins>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<version>${maven.compiler.plugin.version}</version>
						<configuration>
							<source>${jdk.source.version.openshift}</source>
							<target>${jdk.compiler.version.openshift}</target>
							<encoding>UTF-8</encoding>
						</configuration>
					</plugin>

					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>${maven.surefire.plugin.version}</version>
						<configuration>
							<argLine>-Xms512m -Xmx1024m</argLine>
							<skipTests>false</skipTests>
							<!-- <argLine>${surefireArgLine}</argLine> -->
							<systemPropertyVariables>
								<surefire.reports.directory>
									${testng.reports.directory}
								</surefire.reports.directory>
								<surefire.reports.profile>
									${my.text} profile id
									=${project.activeProfiles[0].id}
								</surefire.reports.profile>
							</systemPropertyVariables>
							<suiteXmlFiles>
								<!-- <suiteXmlFile>testng.xml</suiteXmlFile> -->
								<file>testng.xml</file>
								<!-- <file>testng1.xml</file> -->
							</suiteXmlFiles>
							<reportsDirectory>${testng.reports.directory}</reportsDirectory>
						</configuration>
					</plugin>

				</plugins>
			</build>
		</profile>

	</profiles>

</project>